apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: auth-ksa
      containers:
        - name: auth
          image: us-central1-docker.pkg.dev/go-poc-58/auth-service-repo/auth-service:latest
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "500Mi"
          env:
            - name: ENV
              value: "dev"
            - name: PROJECT_ID
              value: "go-poc-58"
            - name: PROJECT_NUMBER
              value: "560574255762"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: LoadBalancer

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: auth-quota
  namespace: auth-service
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "1Gi"
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "5"